CREATE TABLE order_products (
    id SERIAL PRIMARY KEY, 
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE ON UPDATE CASCADE, 
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE ON UPDATE CASCADE, 
    quantity INTEGER NOT NULL DEFAULT 1
    );